In [65]:
import os
import cv2
import numpy as np

In [66]:
fold = ['Mohit', 'Sahil', 'Sarthak']

In [67]:
import os
import cv2

folders = ["Mohit", "Sahil", "Sarthak"]

label = []
images = []

for i, folder in enumerate(folders):
    print(folder)
    for file in os.listdir(folder):
        # load the image
        img = cv2.imread(os.path.join(folder, file))
        # convert to grayscale
        #img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        # add to list
        images.append(img)
        label.append(i)

Mohit
Sahil
Sarthak


In [68]:
import pandas as pd

pd.DataFrame(label).value_counts()

1    10
2     9
0     8
dtype: int64

In [69]:
images[0]

array([[[209, 195, 172],
        [212, 198, 175],
        [212, 199, 177],
        ...,
        [139, 138, 142],
        [139, 138, 142],
        [140, 139, 143]],

       [[211, 197, 174],
        [214, 200, 177],
        [215, 201, 179],
        ...,
        [142, 141, 145],
        [145, 144, 148],
        [146, 145, 149]],

       [[213, 197, 174],
        [215, 199, 176],
        [217, 200, 179],
        ...,
        [142, 141, 145],
        [146, 145, 149],
        [148, 147, 151]],

       ...,

       [[205, 181, 145],
        [206, 182, 146],
        [208, 183, 149],
        ...,
        [ 35,  21,  22],
        [ 38,  22,  23],
        [ 40,  22,  23]],

       [[205, 181, 145],
        [206, 182, 146],
        [208, 183, 149],
        ...,
        [ 34,  20,  21],
        [ 36,  20,  21],
        [ 36,  20,  21]],

       [[205, 181, 145],
        [206, 182, 146],
        [208, 183, 149],
        ...,
        [ 30,  18,  18],
        [ 32,  16,  17],
        [ 32,  16,  17]]

### Resize

In [70]:
images = [cv2.resize(img, (400, 400)) for img in images]

In [71]:
images = [image/255.0 for image in images]

In [72]:
images = np.array(images)

In [73]:
images.shape

(27, 400, 400, 3)

In [74]:
images[0].shape

(400, 400, 3)

In [75]:
label = np.array(label)
label.shape

(27,)

In [76]:
def convert_to_one_hot(Y, C):
  Y = np.eye(C)[Y.reshape(-1)]
  return Y

In [111]:
# from tensorflow.keras.utils import to_categorical

In [112]:
# label = to_categorical(label)

In [113]:
# label = label[:, 2:]

In [77]:
min(label)

0

In [78]:
label = label-min(label)

In [79]:
label.reshape(-1)

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2])

In [80]:
label = convert_to_one_hot(label, 3)

In [81]:
images= images+images

In [82]:
label = label+label

In [83]:
import tensorflow as tf
from tensorflow import keras
from keras import layers as tfl

In [84]:
input_shape = (400,400,3)

In [85]:
model = keras.Sequential([
    tfl.Conv2D(filters = 8, kernel_size = 7, strides = 1, padding = 'same', input_shape = input_shape),
    tfl.ReLU(),
    tfl.MaxPooling2D(pool_size = 8, strides = 8, padding = 'same'),
    tfl.Conv2D(filters = 16, kernel_size = 2, strides = 1, padding = 'same'),
    tfl.ReLU(),
    tfl.MaxPooling2D(pool_size = 4, strides = 4, padding = 'same'),
    tfl.Flatten(),
    tfl.Dense(3, activation = 'softmax')
])

In [86]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_4 (Conv2D)           (None, 400, 400, 8)       1184      
                                                                 
 re_lu_4 (ReLU)              (None, 400, 400, 8)       0         
                                                                 
 max_pooling2d_4 (MaxPooling  (None, 50, 50, 8)        0         
 2D)                                                             
                                                                 
 conv2d_5 (Conv2D)           (None, 50, 50, 16)        528       
                                                                 
 re_lu_5 (ReLU)              (None, 50, 50, 16)        0         
                                                                 
 max_pooling2d_5 (MaxPooling  (None, 13, 13, 16)       0         
 2D)                                                  

In [87]:
model.compile(
    optimizer='Adam',
    metrics=['acc'],
    loss='categorical_crossentropy'
)

In [88]:
train_dataset = tf.data.Dataset.from_tensor_slices((images, label)).batch(4)

In [89]:
history = model.fit(train_dataset, epochs=12)

Epoch 1/12
7/7 [==============================] - 3s 279ms/step - loss: 5.1213 - acc: 0.2963
Epoch 2/12
7/7 [==============================] - 2s 273ms/step - loss: 1.8085 - acc: 0.5556
Epoch 3/12
7/7 [==============================] - 2s 295ms/step - loss: 1.7756 - acc: 0.3704
Epoch 4/12
7/7 [==============================] - 3s 359ms/step - loss: 1.6416 - acc: 0.7037
Epoch 5/12
7/7 [==============================] - 3s 359ms/step - loss: 1.4527 - acc: 0.7037
Epoch 6/12
7/7 [==============================] - 3s 355ms/step - loss: 1.4983 - acc: 0.6667
Epoch 7/12
7/7 [==============================] - 3s 359ms/step - loss: 0.3004 - acc: 0.9630
Epoch 8/12
7/7 [==============================] - 3s 355ms/step - loss: 7.9308 - acc: 0.4815
Epoch 9/12
7/7 [==============================] - 3s 358ms/step - loss: 2.5164 - acc: 0.7037
Epoch 10/12
7/7 [==============================] - 2s 355ms/step - loss: 1.4302 - acc: 0.8148
Epoch 11/12
7/7 [==============================] - 3s 358ms/step - lo

In [95]:
def findName(ee):
  if ee==0:
    return "Mohit"
  if ee==1:
    return "Sahil"
  if ee==2:
    return "Sarthak"

In [96]:
model.evaluate(images, label)

1/1 [==============================] - 0s 355ms/step - loss: 2.4459 - acc: 0.8519


[2.445878505706787, 0.8518518805503845]

In [97]:
ans = [findName(np.argmax(i)) for i in model.predict(images)]

1/1 [==============================] - 0s 341ms/step


In [98]:
ans

['Mohit',
 'Sarthak',
 'Sarthak',
 'Sarthak',
 'Mohit',
 'Sarthak',
 'Mohit',
 'Mohit',
 'Sahil',
 'Sahil',
 'Sahil',
 'Sahil',
 'Sahil',
 'Sahil',
 'Sahil',
 'Sahil',
 'Sahil',
 'Sahil',
 'Sarthak',
 'Sarthak',
 'Sarthak',
 'Sarthak',
 'Sarthak',
 'Sarthak',
 'Sarthak',
 'Sarthak',
 'Sarthak']

In [94]:
label

array([[2., 0., 0.],
       [2., 0., 0.],
       [2., 0., 0.],
       [2., 0., 0.],
       [2., 0., 0.],
       [2., 0., 0.],
       [2., 0., 0.],
       [2., 0., 0.],
       [0., 2., 0.],
       [0., 2., 0.],
       [0., 2., 0.],
       [0., 2., 0.],
       [0., 2., 0.],
       [0., 2., 0.],
       [0., 2., 0.],
       [0., 2., 0.],
       [0., 2., 0.],
       [0., 2., 0.],
       [0., 0., 2.],
       [0., 0., 2.],
       [0., 0., 2.],
       [0., 0., 2.],
       [0., 0., 2.],
       [0., 0., 2.],
       [0., 0., 2.],
       [0., 0., 2.],
       [0., 0., 2.]])